id: workspace-snapshot
version: "6.3.3"
name: Repo Action Plan
description: Build an evidence-based, executable action plan from repository signals using small deterministic steps.

inputs:
  - name: goal
    type: string
    required: false
    default: "stabilize and improve repo quality"

steps:
  - id: seed-context
    name: Seed Context
    type: system_write_file
    path: .tmp/workflow-artifacts/context.md
    content: |
      # Workflow Goal
      {{args.goal}}
    dependsOn: []
    outputs:
      - .tmp/workflow-artifacts/context.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/context.md
      - type: file_contains
        path: .tmp/workflow-artifacts/context.md
        text: "# Workflow Goal"
    onFail: fail_run
    retries: 0

  - id: capture-branch
    name: Capture Branch
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `mkdir -p .ferretbot/.tmp/workflow-artifacts/repo && (git branch --show-current > .ferretbot/.tmp/workflow-artifacts/repo/branch.txt || printf 'unknown' > .ferretbot/.tmp/workflow-artifacts/repo/branch.txt)`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - seed-context
    outputs:
      - .tmp/workflow-artifacts/repo/branch.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/repo/branch.txt
      - type: file_regex
        path: .tmp/workflow-artifacts/repo/branch.txt
        pattern: ".+"
    onFail: fail_run
    retries: 1

  - id: capture-git-status
    name: Capture Git Status
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `mkdir -p .ferretbot/.tmp/workflow-artifacts/repo && (git status --short > .ferretbot/.tmp/workflow-artifacts/repo/git-status.txt || printf 'unknown' > .ferretbot/.tmp/workflow-artifacts/repo/git-status.txt)`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - seed-context
    outputs:
      - .tmp/workflow-artifacts/repo/git-status.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/repo/git-status.txt
    onFail: fail_run
    retries: 1

  - id: capture-top-level-layout
    name: Capture Top-Level Layout
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `mkdir -p .ferretbot/.tmp/workflow-artifacts/repo && (ls -1 > .ferretbot/.tmp/workflow-artifacts/repo/top-level-layout.txt || printf 'unknown' > .ferretbot/.tmp/workflow-artifacts/repo/top-level-layout.txt)`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - seed-context
    outputs:
      - .tmp/workflow-artifacts/repo/top-level-layout.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/repo/top-level-layout.txt
      - type: file_regex
        path: .tmp/workflow-artifacts/repo/top-level-layout.txt
        pattern: ".+"
    onFail: fail_run
    retries: 1

  - id: capture-workflow-inventory
    name: Capture Workflow Inventory
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `mkdir -p .ferretbot/.tmp/workflow-artifacts/repo && (ls -1 .ferretbot/workflows > .ferretbot/.tmp/workflow-artifacts/repo/workflow-inventory.txt || printf 'unknown' > .ferretbot/.tmp/workflow-artifacts/repo/workflow-inventory.txt)`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - seed-context
    outputs:
      - .tmp/workflow-artifacts/repo/workflow-inventory.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/repo/workflow-inventory.txt
      - type: file_regex
        path: .tmp/workflow-artifacts/repo/workflow-inventory.txt
        pattern: ".+"
    onFail: fail_run
    retries: 1

  - id: write-repo-state
    name: Write Repo State
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `mkdir -p .ferretbot/.tmp/workflow-artifacts && { printf '## Repo State\n\n### Branch\n'; cat .ferretbot/.tmp/workflow-artifacts/repo/branch.txt; printf '\n### Git Status\n'; cat .ferretbot/.tmp/workflow-artifacts/repo/git-status.txt; printf '\n### Top-Level Layout\n'; cat .ferretbot/.tmp/workflow-artifacts/repo/top-level-layout.txt; printf '\n### Workflow Inventory\n'; cat .ferretbot/.tmp/workflow-artifacts/repo/workflow-inventory.txt; } > .ferretbot/.tmp/workflow-artifacts/repo-state.md`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - capture-branch
      - capture-git-status
      - capture-top-level-layout
      - capture-workflow-inventory
    outputs:
      - .tmp/workflow-artifacts/repo-state.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/repo-state.md
      - type: file_contains
        path: .tmp/workflow-artifacts/repo-state.md
        text: "## Repo State"
      - type: file_contains
        path: .tmp/workflow-artifacts/repo-state.md
        text: "### Branch"
      - type: file_contains
        path: .tmp/workflow-artifacts/repo-state.md
        text: "### Git Status"
      - type: file_contains
        path: .tmp/workflow-artifacts/repo-state.md
        text: "workspace-snapshot"
    onFail: fail_run
    retries: 1

  - id: capture-test-signal
    name: Capture Test Signal
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `mkdir -p .ferretbot/.tmp/workflow-artifacts && (npm test > .ferretbot/.tmp/workflow-artifacts/test-output.log 2>&1; code=$?; pass_line=$(grep -m1 '# pass ' .ferretbot/.tmp/workflow-artifacts/test-output.log || true); fail_line=$(grep -m1 '# fail ' .ferretbot/.tmp/workflow-artifacts/test-output.log || true); printf '## Test Signal\n\n### Command\n`npm test`\n\n### Exit Code\n%s\n\n### Key Output\n%s\n%s\n' "$code" "${pass_line:-# pass unknown}" "${fail_line:-# fail unknown}" > .ferretbot/.tmp/workflow-artifacts/test-signal.md; rm -f .ferretbot/.tmp/workflow-artifacts/test-output.log)`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - write-repo-state
    outputs:
      - .tmp/workflow-artifacts/test-signal.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/test-signal.md
      - type: file_contains
        path: .tmp/workflow-artifacts/test-signal.md
        text: "## Test Signal"
      - type: file_contains
        path: .tmp/workflow-artifacts/test-signal.md
        text: "### Exit Code"
      - type: file_contains
        path: .tmp/workflow-artifacts/test-signal.md
        text: "# pass"
    onFail: fail_run
    retries: 1

  - id: capture-package-signal
    name: Capture Package Signal
    type: agent
    instruction: |
      Read exactly one input file: `package.json`.

      Write exactly one file:
      - `.ferretbot/.tmp/workflow-artifacts/package-signal.md`

      Required headings:
      - ## Package Signal
      - ### Scripts
      - ### Dependencies
      - ### Engines

      Rules:
      - Use observed values only.
      - If a field is absent, write "none".
      - Do not run bash commands.

      Path contract:
      - Use the exact literal output path shown above.
      - Forbidden path variants: `/.ferretbot/...`, `\.ferretbot/...`, `./.ferretbot/...`.
      - Do not create or write any other files.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - write-repo-state
    outputs:
      - .tmp/workflow-artifacts/package-signal.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/package-signal.md
      - type: file_contains
        path: .tmp/workflow-artifacts/package-signal.md
        text: "## Package Signal"
      - type: file_contains
        path: .tmp/workflow-artifacts/package-signal.md
        text: "### Scripts"
    onFail: fail_run
    retries: 1

  - id: build-action-plan
    name: Build Action Plan
    type: agent
    instruction: |
      Write exactly one file:
      - `.ferretbot/.tmp/workflow-artifacts/ACTION_PLAN.md`

      Read:
      - `.ferretbot/.tmp/workflow-artifacts/repo-state.md`
      - `.ferretbot/.tmp/workflow-artifacts/test-signal.md`
      - `.ferretbot/.tmp/workflow-artifacts/package-signal.md`
      - `.ferretbot/.tmp/workflow-artifacts/context.md`

      Required headings (exact):
      - ## Action Plan
      - ### Current State
      - ### Top 3 Actions
      - ### Action Details
      - ### Verification Commands

      Rules:
      - Exactly 3 actions, highest impact first.
      - Each action must include:
        - why (evidence reference)
        - change target (file/module)
        - command to verify
        - Evidence: <exact quoted line from artifact> (<artifact path>)
      - Use only facts present in these artifacts:
        - `.ferretbot/.tmp/workflow-artifacts/repo-state.md`
        - `.ferretbot/.tmp/workflow-artifacts/test-signal.md`
        - `.ferretbot/.tmp/workflow-artifacts/package-signal.md`
      - Do not claim frameworks, files, or tools that are not present in artifacts.
      - Actions must be concrete and executable.
      - Do not run bash commands.

      Path contract:
      - Use the exact literal output path shown above.
      - Do not create or write any other files.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - capture-test-signal
      - capture-package-signal
    outputs:
      - .tmp/workflow-artifacts/ACTION_PLAN.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/ACTION_PLAN.md
      - type: file_contains
        path: .tmp/workflow-artifacts/ACTION_PLAN.md
        text: "## Action Plan"
      - type: file_contains
        path: .tmp/workflow-artifacts/ACTION_PLAN.md
        text: "### Top 3 Actions"
      - type: file_contains
        path: .tmp/workflow-artifacts/ACTION_PLAN.md
        text: "### Verification Commands"
      - type: file_contains
        path: .tmp/workflow-artifacts/ACTION_PLAN.md
        text: "Evidence:"
    onFail: blocked
    retries: 1

  - id: verify-plan
    name: Verify Plan
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `plan=.ferretbot/.tmp/workflow-artifacts/ACTION_PLAN.md; out=.ferretbot/.tmp/workflow-artifacts/verification.txt; if [ ! -f "$plan" ]; then printf 'VERIFY_FAIL: missing action plan\n' > "$out"; elif ! grep -q '^## Action Plan' "$plan"; then printf 'VERIFY_FAIL: missing Action Plan heading\n' > "$out"; elif ! grep -q '^### Top 3 Actions' "$plan"; then printf 'VERIFY_FAIL: missing Top 3 Actions heading\n' > "$out"; elif ! grep -q '^### Verification Commands' "$plan"; then printf 'VERIFY_FAIL: missing Verification Commands heading\n' > "$out"; elif [ "$(grep -E '^[1-3]\\. ' "$plan" | wc -l)" -ne 3 ]; then printf 'VERIFY_FAIL: expected exactly 3 numbered actions\n' > "$out"; elif [ "$(grep -c 'Evidence:' "$plan")" -lt 3 ]; then printf 'VERIFY_FAIL: missing evidence lines\n' > "$out"; else printf 'VERIFY_OK\n' > "$out"; fi`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - build-action-plan
    outputs:
      - .tmp/workflow-artifacts/verification.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/verification.txt
      - type: file_contains
        path: .tmp/workflow-artifacts/verification.txt
        text: "VERIFY_OK"
    onFail: blocked
    retries: 1
