id: workspace-snapshot
version: "4.0.0"
name: Workspace Snapshot
description: Collect facts, write STATUS.md, and verify accuracy with explicit step contracts.
steps:
  - id: collect-facts
    name: Collect Facts
    type: agent
    instruction: |
      Collect factual project data and write it to facts.md at repository root.

      Required sections in facts.md (exact headings):
      - ## Facts
      - ### Branch
      - ### Git Status
      - ### Top-Level Layout
      - ### Test File Sample
      - ### Scripts
      - ### Gitignore Node Modules Rule

      Use tools only; do not guess:
      - branch: git branch --show-current
      - status: git status --short
      - layout: list top-level files/dirs
      - tests: find test -type f | head -n 10
      - scripts: read package.json and extract scripts
      - gitignore rule: read .gitignore and determine whether node_modules/ is present

      Requirements:
      - facts.md must contain only observed facts.
      - If a command fails, write "unknown" for that field.
      - Write facts.md using the write tool.
    tools:
      - bash
      - read
      - write
    loadSkills: []
    dependsOn: []
    outputs:
      - facts.md
    doneWhen:
      - type: file_exists
        path: facts.md
      - type: file_contains
        path: facts.md
        text: "## Facts"
      - type: file_contains
        path: facts.md
        text: "### Branch"
      - type: file_contains
        path: facts.md
        text: "### Git Status"
      - type: file_contains
        path: facts.md
        text: "### Top-Level Layout"
      - type: file_contains
        path: facts.md
        text: "### Test File Sample"
      - type: file_contains
        path: facts.md
        text: "### Scripts"
      - type: file_contains
        path: facts.md
        text: "### Gitignore Node Modules Rule"
    onFail: fail_run
    retries: 2

  - id: write-status
    name: Write STATUS.md
    type: agent
    instruction: |
      Read facts.md and generate STATUS.md at repository root.

      Required headings in STATUS.md (exact):
      - ## Project Snapshot
      - ### Branch & Status
      - ### Top-Level Layout
      - ### Scripts
      - ### Risks / Notes

      Rules:
      - Use only facts from facts.md.
      - Do not add claims not present in facts.md.
      - If a fact is missing, say "unknown".
      - Keep concise and factual.

      Write STATUS.md using the write tool.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - collect-facts
    outputs:
      - STATUS.md
    doneWhen:
      - type: file_exists
        path: STATUS.md
      - type: file_contains
        path: STATUS.md
        text: "## Project Snapshot"
      - type: file_contains
        path: STATUS.md
        text: "### Branch & Status"
      - type: file_contains
        path: STATUS.md
        text: "### Top-Level Layout"
      - type: file_contains
        path: STATUS.md
        text: "### Scripts"
      - type: file_contains
        path: STATUS.md
        text: "### Risks / Notes"
    onFail: fail_run
    retries: 2

  - id: verify-status
    name: Verify STATUS.md
    type: agent
    instruction: |
      Read facts.md and STATUS.md.
      Verify STATUS.md is consistent with facts.md.

      Minimum checks:
      - All required STATUS.md headings exist.
      - Branch matches facts.md branch.
      - Git clean/dirty statement matches facts.md git status.
      - STATUS.md does not claim no tests if facts.md test sample contains entries.
      - STATUS.md does not suggest adding node_modules to .gitignore if facts.md says node_modules/ is present.

      Write one line to verification.txt at repository root:
      - VERIFY_OK
      OR
      - VERIFY_FAIL: <reason>
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - write-status
    outputs:
      - verification.txt
    doneWhen:
      - type: file_exists
        path: verification.txt
      - type: file_contains
        path: verification.txt
        text: VERIFY_OK
    onFail: fail_run
    retries: 0
