id: workspace-snapshot
version: "6.0.0"
name: Repo Action Plan
description: Build an evidence-based, executable action plan from repository signals using small deterministic steps.

inputs:
  - name: goal
    type: string
    required: false
    default: "stabilize and improve repo quality"

steps:
  - id: seed-context
    name: Seed Context
    type: system_write_file
    path: .tmp/workflow-artifacts/context.md
    content: |
      # Workflow Goal
      {{args.goal}}
    dependsOn: []
    outputs:
      - .tmp/workflow-artifacts/context.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/context.md
      - type: file_contains
        path: .tmp/workflow-artifacts/context.md
        text: "# Workflow Goal"
    onFail: fail_run
    retries: 0

  - id: capture-repo-state
    name: Capture Repo State
    type: agent
    instruction: |
      Use tools only and write `.tmp/workflow-artifacts/repo-state.md`.

      Collect:
      - branch (`git branch --show-current`)
      - git status (`git status --short`)
      - top-level files/dirs (`ls -1`)
      - workflow directories (`ls -1 .ferretbot/workflows`)

      Required headings (exact):
      - ## Repo State
      - ### Branch
      - ### Git Status
      - ### Top-Level Layout
      - ### Workflow Inventory

      Rules:
      - Only observed facts.
      - If a command fails, write "unknown" for that field.
    tools:
      - bash
      - write
    loadSkills: []
    dependsOn:
      - seed-context
    outputs:
      - .tmp/workflow-artifacts/repo-state.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/repo-state.md
      - type: file_contains
        path: .tmp/workflow-artifacts/repo-state.md
        text: "## Repo State"
      - type: file_contains
        path: .tmp/workflow-artifacts/repo-state.md
        text: "### Git Status"
    onFail: fail_run
    retries: 1

  - id: capture-test-signal
    name: Capture Test Signal
    type: agent
    instruction: |
      Run `npm test` once and write `.tmp/workflow-artifacts/test-signal.md`.

      Required headings:
      - ## Test Signal
      - ### Command
      - ### Exit Code
      - ### Key Output

      Rules:
      - Use observed command output only.
      - Include short key output excerpt (stdout/stderr summary).
      - If command fails to run, record exit code and reason.
    tools:
      - bash
      - write
    loadSkills: []
    dependsOn:
      - capture-repo-state
    outputs:
      - .tmp/workflow-artifacts/test-signal.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/test-signal.md
      - type: file_contains
        path: .tmp/workflow-artifacts/test-signal.md
        text: "## Test Signal"
      - type: file_contains
        path: .tmp/workflow-artifacts/test-signal.md
        text: "### Exit Code"
    onFail: fail_run
    retries: 1

  - id: capture-package-signal
    name: Capture Package Signal
    type: agent
    instruction: |
      Read `package.json` and write `.tmp/workflow-artifacts/package-signal.md`.

      Required headings:
      - ## Package Signal
      - ### Scripts
      - ### Dependencies
      - ### Engines

      Rules:
      - Use observed values only.
      - If a field is absent, write "none".
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - capture-repo-state
    outputs:
      - .tmp/workflow-artifacts/package-signal.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/package-signal.md
      - type: file_contains
        path: .tmp/workflow-artifacts/package-signal.md
        text: "## Package Signal"
      - type: file_contains
        path: .tmp/workflow-artifacts/package-signal.md
        text: "### Scripts"
    onFail: fail_run
    retries: 1

  - id: build-action-plan
    name: Build Action Plan
    type: agent
    instruction: |
      Read:
      - `.tmp/workflow-artifacts/repo-state.md`
      - `.tmp/workflow-artifacts/test-signal.md`
      - `.tmp/workflow-artifacts/package-signal.md`
      - `.tmp/workflow-artifacts/context.md`

      Write `ACTION_PLAN.md` at repository root.

      Required headings (exact):
      - ## Action Plan
      - ### Current State
      - ### Top 3 Actions
      - ### Action Details
      - ### Verification Commands

      Rules:
      - Exactly 3 actions, highest impact first.
      - Each action must include:
        - why (evidence reference)
        - change target (file/module)
        - command to verify
      - Actions must be concrete and executable.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - capture-test-signal
      - capture-package-signal
    outputs:
      - ACTION_PLAN.md
    doneWhen:
      - type: file_exists
        path: ACTION_PLAN.md
      - type: file_contains
        path: ACTION_PLAN.md
        text: "## Action Plan"
      - type: file_contains
        path: ACTION_PLAN.md
        text: "### Top 3 Actions"
      - type: file_contains
        path: ACTION_PLAN.md
        text: "### Verification Commands"
    onFail: blocked
    retries: 1

  - id: verify-plan
    name: Verify Plan
    type: agent
    instruction: |
      Verify `ACTION_PLAN.md` against all workflow artifacts and write `.tmp/workflow-artifacts/verification.txt`.

      Write exactly one line:
      - VERIFY_OK
      OR
      - VERIFY_FAIL: <reason>

      Minimum checks:
      - ACTION_PLAN.md has all required headings.
      - Exactly 3 actions are present.
      - Every action references observed evidence from artifacts.
      - Every action includes a concrete verification command.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - build-action-plan
    outputs:
      - .tmp/workflow-artifacts/verification.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/verification.txt
      - type: file_contains
        path: .tmp/workflow-artifacts/verification.txt
        text: "VERIFY_OK"
    onFail: blocked
    retries: 1
