id: workspace-snapshot
version: "6.3.0"
name: Repo Action Plan
description: Build an evidence-based, executable action plan from repository signals using small deterministic steps.

inputs:
  - name: goal
    type: string
    required: false
    default: "stabilize and improve repo quality"

steps:
  - id: seed-context
    name: Seed Context
    type: system_write_file
    path: .tmp/workflow-artifacts/context.md
    content: |
      # Workflow Goal
      {{args.goal}}
    dependsOn: []
    outputs:
      - .tmp/workflow-artifacts/context.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/context.md
      - type: file_contains
        path: .tmp/workflow-artifacts/context.md
        text: "# Workflow Goal"
    onFail: fail_run
    retries: 0

  - id: capture-branch
    name: Capture Branch
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `mkdir -p .ferretbot/.tmp/workflow-artifacts/repo && (git branch --show-current > .ferretbot/.tmp/workflow-artifacts/repo/branch.txt || printf 'unknown' > .ferretbot/.tmp/workflow-artifacts/repo/branch.txt)`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - seed-context
    outputs:
      - .tmp/workflow-artifacts/repo/branch.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/repo/branch.txt
      - type: file_regex
        path: .tmp/workflow-artifacts/repo/branch.txt
        pattern: ".+"
    onFail: fail_run
    retries: 1

  - id: capture-git-status
    name: Capture Git Status
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `mkdir -p .ferretbot/.tmp/workflow-artifacts/repo && (git status --short > .ferretbot/.tmp/workflow-artifacts/repo/git-status.txt || printf 'unknown' > .ferretbot/.tmp/workflow-artifacts/repo/git-status.txt)`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - seed-context
    outputs:
      - .tmp/workflow-artifacts/repo/git-status.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/repo/git-status.txt
    onFail: fail_run
    retries: 1

  - id: capture-top-level-layout
    name: Capture Top-Level Layout
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `mkdir -p .ferretbot/.tmp/workflow-artifacts/repo && (ls -1 > .ferretbot/.tmp/workflow-artifacts/repo/top-level-layout.txt || printf 'unknown' > .ferretbot/.tmp/workflow-artifacts/repo/top-level-layout.txt)`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - seed-context
    outputs:
      - .tmp/workflow-artifacts/repo/top-level-layout.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/repo/top-level-layout.txt
      - type: file_regex
        path: .tmp/workflow-artifacts/repo/top-level-layout.txt
        pattern: ".+"
    onFail: fail_run
    retries: 1

  - id: capture-workflow-inventory
    name: Capture Workflow Inventory
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `mkdir -p .ferretbot/.tmp/workflow-artifacts/repo && (ls -1 .ferretbot/workflows > .ferretbot/.tmp/workflow-artifacts/repo/workflow-inventory.txt || printf 'unknown' > .ferretbot/.tmp/workflow-artifacts/repo/workflow-inventory.txt)`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - seed-context
    outputs:
      - .tmp/workflow-artifacts/repo/workflow-inventory.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/repo/workflow-inventory.txt
      - type: file_regex
        path: .tmp/workflow-artifacts/repo/workflow-inventory.txt
        pattern: ".+"
    onFail: fail_run
    retries: 1

  - id: write-repo-state
    name: Write Repo State
    type: agent
    instruction: |
      Write exactly one file:
      - `.ferretbot/.tmp/workflow-artifacts/repo-state.md`

      Read these files:
      - `.ferretbot/.tmp/workflow-artifacts/repo/branch.txt`
      - `.ferretbot/.tmp/workflow-artifacts/repo/git-status.txt`
      - `.ferretbot/.tmp/workflow-artifacts/repo/top-level-layout.txt`
      - `.ferretbot/.tmp/workflow-artifacts/repo/workflow-inventory.txt`

      Required headings (exact):
      - ## Repo State
      - ### Branch
      - ### Git Status
      - ### Top-Level Layout
      - ### Workflow Inventory

      Tool constraints:
      - Do not run bash.
      - Use only the read files above as source evidence.

      Path contract:
      - Use the exact literal output path shown above.
      - Forbidden path variants: `/.ferretbot/...`, `\.ferretbot/...`, `./.ferretbot/...`.
      - Do not create or write any other files.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - capture-branch
      - capture-git-status
      - capture-top-level-layout
      - capture-workflow-inventory
    outputs:
      - .tmp/workflow-artifacts/repo-state.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/repo-state.md
      - type: file_contains
        path: .tmp/workflow-artifacts/repo-state.md
        text: "## Repo State"
      - type: file_contains
        path: .tmp/workflow-artifacts/repo-state.md
        text: "### Branch"
      - type: file_contains
        path: .tmp/workflow-artifacts/repo-state.md
        text: "### Git Status"
    onFail: fail_run
    retries: 1

  - id: capture-test-signal
    name: Capture Test Signal
    type: agent
    instruction: |
      Execute exactly one command: `npm test`.

      Write exactly one file:
      - `.ferretbot/.tmp/workflow-artifacts/test-signal.md`

      Required headings:
      - ## Test Signal
      - ### Command
      - ### Exit Code
      - ### Key Output

      Rules:
      - Use observed command output only.
      - Include short key output excerpt (stdout/stderr summary).
      - If command fails to run, record exit code and reason.
      - Do not run additional commands.

      Path contract:
      - Use the exact literal output path shown above.
      - Forbidden path variants: `/.ferretbot/...`, `\.ferretbot/...`, `./.ferretbot/...`.
      - Do not create or write any other files.
    tools:
      - bash
      - write
    loadSkills: []
    dependsOn:
      - write-repo-state
    outputs:
      - .tmp/workflow-artifacts/test-signal.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/test-signal.md
      - type: file_contains
        path: .tmp/workflow-artifacts/test-signal.md
        text: "## Test Signal"
      - type: file_contains
        path: .tmp/workflow-artifacts/test-signal.md
        text: "### Exit Code"
    onFail: fail_run
    retries: 1

  - id: capture-package-signal
    name: Capture Package Signal
    type: agent
    instruction: |
      Read exactly one input file: `package.json`.

      Write exactly one file:
      - `.ferretbot/.tmp/workflow-artifacts/package-signal.md`

      Required headings:
      - ## Package Signal
      - ### Scripts
      - ### Dependencies
      - ### Engines

      Rules:
      - Use observed values only.
      - If a field is absent, write "none".
      - Do not run bash commands.

      Path contract:
      - Use the exact literal output path shown above.
      - Forbidden path variants: `/.ferretbot/...`, `\.ferretbot/...`, `./.ferretbot/...`.
      - Do not create or write any other files.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - write-repo-state
    outputs:
      - .tmp/workflow-artifacts/package-signal.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/package-signal.md
      - type: file_contains
        path: .tmp/workflow-artifacts/package-signal.md
        text: "## Package Signal"
      - type: file_contains
        path: .tmp/workflow-artifacts/package-signal.md
        text: "### Scripts"
    onFail: fail_run
    retries: 1

  - id: build-action-plan
    name: Build Action Plan
    type: agent
    instruction: |
      Write exactly one file:
      - `ACTION_PLAN.md`

      Read:
      - `.ferretbot/.tmp/workflow-artifacts/repo-state.md`
      - `.ferretbot/.tmp/workflow-artifacts/test-signal.md`
      - `.ferretbot/.tmp/workflow-artifacts/package-signal.md`
      - `.ferretbot/.tmp/workflow-artifacts/context.md`

      Required headings (exact):
      - ## Action Plan
      - ### Current State
      - ### Top 3 Actions
      - ### Action Details
      - ### Verification Commands

      Rules:
      - Exactly 3 actions, highest impact first.
      - Each action must include:
        - why (evidence reference)
        - change target (file/module)
        - command to verify
      - Actions must be concrete and executable.
      - Do not run bash commands.

      Path contract:
      - Use the exact literal output path shown above.
      - Do not create or write any other files.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - capture-test-signal
      - capture-package-signal
    outputs:
      - ACTION_PLAN.md
    doneWhen:
      - type: file_exists
        path: ACTION_PLAN.md
      - type: file_contains
        path: ACTION_PLAN.md
        text: "## Action Plan"
      - type: file_contains
        path: ACTION_PLAN.md
        text: "### Top 3 Actions"
      - type: file_contains
        path: ACTION_PLAN.md
        text: "### Verification Commands"
    onFail: blocked
    retries: 1

  - id: verify-plan
    name: Verify Plan
    type: agent
    instruction: |
      Read `ACTION_PLAN.md` and all workflow artifacts, then verify consistency.

      Write exactly one file:
      - `.ferretbot/.tmp/workflow-artifacts/verification.txt`

      Write exactly one line:
      - VERIFY_OK
      OR
      - VERIFY_FAIL: <reason>

      Minimum checks:
      - ACTION_PLAN.md has all required headings.
      - Exactly 3 actions are present.
      - Every action references observed evidence from artifacts.
      - Every action includes a concrete verification command.

      Path contract:
      - Use the exact literal output path shown above.
      - Forbidden path variants: `/.ferretbot/...`, `\.ferretbot/...`, `./.ferretbot/...`.
      - Do not create or write any other files.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - build-action-plan
    outputs:
      - .tmp/workflow-artifacts/verification.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/verification.txt
      - type: file_contains
        path: .tmp/workflow-artifacts/verification.txt
        text: "VERIFY_OK"
    onFail: blocked
    retries: 1
