id: workspace-snapshot
version: "5.0.0"
name: Workspace Intelligence Snapshot
description: Produce a multi-artifact project snapshot with evidence, risk analysis, and verification gates.

inputs:
  - name: focus
    type: string
    required: false
    default: "overall project health"
  - name: includeTests
    type: boolean
    required: false
    default: true
  - name: includeRisks
    type: boolean
    required: false
    default: true

steps:
  - id: seed-run-context
    name: Seed Run Context
    type: system_write_file
    path: .tmp/workflow-artifacts/run-context.md
    content: |
      # Workspace Snapshot Run Context
      - Focus: {{args.focus}}
      - includeTests: {{args.includeTests}}
      - includeRisks: {{args.includeRisks}}
    dependsOn: []
    outputs:
      - .tmp/workflow-artifacts/run-context.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/run-context.md
      - type: file_contains
        path: .tmp/workflow-artifacts/run-context.md
        text: "# Workspace Snapshot Run Context"
    onFail: fail_run
    retries: 0

  - id: collect-facts
    name: Collect Facts
    type: agent
    instruction: |
      Collect factual repository data and write TWO files:
      1) `.tmp/workflow-artifacts/facts.md`
      2) `.tmp/workflow-artifacts/facts.json`

      Required sections in facts.md (exact headings):
      - ## Facts
      - ### Branch
      - ### Git Status
      - ### Top-Level Layout
      - ### Test File Sample
      - ### Scripts
      - ### Workflow Inventory
      - ### Tooling Notes

      Required keys in facts.json:
      - branch
      - gitStatus
      - topLevelLayout
      - testFileSample
      - scripts
      - workflowInventory
      - toolingNotes

      Use tools only; do not guess:
      - branch: git branch --show-current
      - status: git status --short
      - layout: list top-level files/dirs
      - tests: find test -type f | head -n 20
      - scripts: read package.json and extract scripts
      - workflows: list .ferretbot/workflows and workflow ids
      - tooling notes: summarize built-in tools from observed source/docs

      Rules:
      - facts.md and facts.json must contain only observed data.
      - If a command fails, store "unknown" for that field.
      - Write both files using the write tool.
    tools:
      - bash
      - read
      - write
    loadSkills: []
    dependsOn:
      - seed-run-context
    outputs:
      - .tmp/workflow-artifacts/facts.md
      - .tmp/workflow-artifacts/facts.json
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/facts.md
      - type: file_contains
        path: .tmp/workflow-artifacts/facts.md
        text: "## Facts"
      - type: file_contains
        path: .tmp/workflow-artifacts/facts.md
        text: "### Workflow Inventory"
      - type: file_exists
        path: .tmp/workflow-artifacts/facts.json
      - type: file_contains
        path: .tmp/workflow-artifacts/facts.json
        text: "\"branch\""
      - type: file_contains
        path: .tmp/workflow-artifacts/facts.json
        text: "\"scripts\""
    onFail: fail_run
    retries: 2

  - id: write-status
    name: Write STATUS.md
    type: agent
    instruction: |
      Read `.tmp/workflow-artifacts/facts.md` and `.tmp/workflow-artifacts/facts.json`.
      Generate `STATUS.md` at repository root.

      Required headings in STATUS.md (exact):
      - ## Project Snapshot
      - ### Branch & Status
      - ### Top-Level Layout
      - ### Scripts
      - ### Workflow Capability
      - ### Risks / Notes

      Rules:
      - Use only facts from the collected artifacts.
      - Do not add claims not present in those artifacts.
      - If a fact is missing, write "unknown".
      - Keep concise and factual.
      - If includeTests is true, include explicit test sample summary.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - collect-facts
    outputs:
      - STATUS.md
    doneWhen:
      - type: file_exists
        path: STATUS.md
      - type: file_contains
        path: STATUS.md
        text: "## Project Snapshot"
      - type: file_contains
        path: STATUS.md
        text: "### Workflow Capability"
      - type: file_contains
        path: STATUS.md
        text: "### Risks / Notes"
    onFail: fail_run
    retries: 2

  - id: write-risk-register
    name: Write Risk Register
    type: agent
    instruction: |
      Read `.tmp/workflow-artifacts/facts.md`, `.tmp/workflow-artifacts/facts.json`, and `STATUS.md`.
      Write `.tmp/workflow-artifacts/risk-register.md`.

      Required headings:
      - ## Risk Register
      - ### High
      - ### Medium
      - ### Low
      - ### Mitigations

      Rules:
      - Include only risks justified by observed repository facts.
      - Each mitigation must be concrete and testable.
      - If includeRisks is false, still create the file and explain that risk detail was minimized.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - write-status
    outputs:
      - .tmp/workflow-artifacts/risk-register.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/risk-register.md
      - type: file_contains
        path: .tmp/workflow-artifacts/risk-register.md
        text: "## Risk Register"
      - type: file_contains
        path: .tmp/workflow-artifacts/risk-register.md
        text: "### Mitigations"
    onFail: fail_run
    retries: 1

  - id: verify-output
    name: Verify Output Pack
    type: agent
    instruction: |
      Verify consistency across:
      - `.tmp/workflow-artifacts/facts.md`
      - `.tmp/workflow-artifacts/facts.json`
      - `STATUS.md`
      - `.tmp/workflow-artifacts/risk-register.md`

      Write `.tmp/workflow-artifacts/verification.txt` with exactly one line:
      - VERIFY_OK
      OR
      - VERIFY_FAIL: <reason>

      Minimum checks:
      - STATUS.md headings exist.
      - STATUS claims are consistent with facts artifacts.
      - Risk register references concrete evidence from facts.
      - No contradiction between branch/status in facts and STATUS.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - write-risk-register
    outputs:
      - .tmp/workflow-artifacts/verification.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/verification.txt
      - type: file_contains
        path: .tmp/workflow-artifacts/verification.txt
        text: "VERIFY_OK"
    onFail: blocked
    retries: 1
