id: agent-docs
version: "1.0.0"
name: Agent Docs
description: Produce grounded documentation for src/agent/* from deterministic file facts.

inputs:
  - name: goal
    type: string
    required: false
    default: "document src/agent modules and flow"

steps:
  - id: seed-context
    name: Seed Context
    type: system_write_file
    path: .tmp/workflow-artifacts/agent-docs/context.md
    content: |
      # Goal
      {{args.goal}}
    dependsOn: []
    outputs:
      - .tmp/workflow-artifacts/agent-docs/context.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/agent-docs/context.md
      - type: file_contains
        path: .tmp/workflow-artifacts/agent-docs/context.md
        text: "# Goal"
    onFail: fail_run
    retries: 0

  - id: capture-agent-facts
    name: Capture Agent Facts
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `mkdir -p .ferretbot/.tmp/workflow-artifacts/agent-docs && { printf '# Agent Facts\n\n'; for f in $(find src/agent -type f | sort); do lines=$(wc -l < "$f"); imports=$(rg -n '^import\\s' "$f" -S | sed 's/^/- /' || true); exports=$(rg -n '^(export\\s+(class|function|const|let|var)|export\\s*\\{)' "$f" -S | sed 's/^/- /' || true); printf '## %s\n' "$f"; printf '- lines: %s\n' "$lines"; printf '- imports:\n%s\n' "${imports:-- (none)}"; printf '- exports:\n%s\n\n' "${exports:-- (none)}"; done; } > .ferretbot/.tmp/workflow-artifacts/agent-docs/agent-facts.md`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - seed-context
    outputs:
      - .tmp/workflow-artifacts/agent-docs/agent-facts.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/agent-docs/agent-facts.md
      - type: file_contains
        path: .tmp/workflow-artifacts/agent-docs/agent-facts.md
        text: "## src/agent/loop/loop.mjs"
      - type: file_contains
        path: .tmp/workflow-artifacts/agent-docs/agent-facts.md
        text: "## src/agent/turn/runner.mjs"
    onFail: fail_run
    retries: 1

  - id: write-agent-docs
    name: Write Agent Docs
    type: agent
    instruction: |
      Read:
      - `.ferretbot/.tmp/workflow-artifacts/agent-docs/context.md`
      - `.ferretbot/.tmp/workflow-artifacts/agent-docs/agent-facts.md`

      Write exactly one file:
      - `.ferretbot/.tmp/workflow-artifacts/agent-docs/AGENT_DOCS.md`

      Required headings (exact):
      - ## src/agent Documentation
      - ### Architecture Overview
      - ### File-by-File Notes
      - ### Event and Turn Flow
      - ### Risks and Gaps

      Rules:
      - Ground every claim in `agent-facts.md`.
      - Under `### File-by-File Notes`, include at least 10 file paths from `src/agent/*`.
      - Do not invent files or exports.
      - Do not run bash.
    tools:
      - read
      - write
    loadSkills: []
    dependsOn:
      - capture-agent-facts
    outputs:
      - .tmp/workflow-artifacts/agent-docs/AGENT_DOCS.md
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/agent-docs/AGENT_DOCS.md
      - type: file_contains
        path: .tmp/workflow-artifacts/agent-docs/AGENT_DOCS.md
        text: "## src/agent Documentation"
      - type: file_contains
        path: .tmp/workflow-artifacts/agent-docs/AGENT_DOCS.md
        text: "### File-by-File Notes"
      - type: file_contains
        path: .tmp/workflow-artifacts/agent-docs/AGENT_DOCS.md
        text: "src/agent/loop/loop.mjs"
    onFail: blocked
    retries: 1

  - id: verify-agent-docs
    name: Verify Agent Docs
    type: agent
    instruction: |
      Execute exactly this single command and nothing else:
      `doc=.ferretbot/.tmp/workflow-artifacts/agent-docs/AGENT_DOCS.md; out=.ferretbot/.tmp/workflow-artifacts/agent-docs/verification.txt; if [ ! -f "$doc" ]; then printf 'VERIFY_FAIL: missing AGENT_DOCS.md\n' > "$out"; elif ! grep -q '^## src/agent Documentation' "$doc"; then printf 'VERIFY_FAIL: missing documentation heading\n' > "$out"; elif ! grep -q '^### File-by-File Notes' "$doc"; then printf 'VERIFY_FAIL: missing file notes heading\n' > "$out"; elif [ "$(grep -c 'src/agent/' "$doc")" -lt 10 ]; then printf 'VERIFY_FAIL: expected at least 10 src/agent file references\n' > "$out"; else printf 'VERIFY_OK\n' > "$out"; fi`
    tools:
      - bash
    loadSkills: []
    dependsOn:
      - write-agent-docs
    outputs:
      - .tmp/workflow-artifacts/agent-docs/verification.txt
    doneWhen:
      - type: file_exists
        path: .tmp/workflow-artifacts/agent-docs/verification.txt
      - type: file_contains
        path: .tmp/workflow-artifacts/agent-docs/verification.txt
        text: "VERIFY_OK"
    onFail: blocked
    retries: 1
